// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0V8yKJiz_KoNGqdRCGwC8tjX0W6YDFvo',
    appId: '1:319188596408:web:e65ad7018f0f6b1386e64d',
    messagingSenderId: '319188596408',
    projectId: 'attendance-70302',
    authDomain: 'attendance-70302.firebaseapp.com',
    storageBucket: 'attendance-70302.appspot.com',
    measurementId: 'G-K9XKDFE656',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPZE5kXtlMGWH7r9YmZqceCWxcAkKwmyM',
    appId: '1:319188596408:android:961827d85ec3d25186e64d',
    messagingSenderId: '319188596408',
    projectId: 'attendance-70302',
    storageBucket: 'attendance-70302.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfFBEPmFVkO6VBnKO9tPSd4LfKbHyYB_c',
    appId: '1:319188596408:ios:591c2f8d70f14d8086e64d',
    messagingSenderId: '319188596408',
    projectId: 'attendance-70302',
    storageBucket: 'attendance-70302.appspot.com',
    iosClientId: '319188596408-sfuo26m0es827l8uqhjaop2fqnc7dhj0.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfFBEPmFVkO6VBnKO9tPSd4LfKbHyYB_c',
    appId: '1:319188596408:ios:591c2f8d70f14d8086e64d',
    messagingSenderId: '319188596408',
    projectId: 'attendance-70302',
    storageBucket: 'attendance-70302.appspot.com',
    iosClientId: '319188596408-sfuo26m0es827l8uqhjaop2fqnc7dhj0.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendance',
  );
}
